### PR TITLE
ENH: List base URIs in settings dialog for users without admin privileges

### PR DESCRIPTION
**Pull request by jotelha**
Also resolves two other minor issues that possibly arose at earlier merges (lookup_tab.connect not asynchronous, access token-entry correctly).

### CODE REVIEW

**Review by pastewka — APPROVED** [review]

**Comment by pastewka** [comment]
Hi @jotelha - please don't make too many changes at this point, I am rehauling the complete code. Merge is pretty much impossible at this point. I'll Backport these fixes here, though.

**Comment by jotelha** [comment]
Aright, won't submit any other changes for now, but before I read that comment just now, I sent another PR...

**Comment by pastewka** [comment]
This PR is now obsolete, correct @jotelha ?

**Comment by jotelha** [comment]
Yes

**Pull request closed without merging**
